

export const TRANSLATIONS = {
  en: {
    appTitle: "Fast",
    appTitleSuffix: "Resume",
    heroTitle: "Optimize your resume",
    heroTitleHighlight: "in seconds",
    heroSubtitle: "Paste your target job description and let our AI tailor your resume to pass ATS filters and stand out to recruiters.",
    step1: "Requirements",
    step2: "Upload",
    step3: "Optimize",
    jdLabel: "Job Description",
    jdPlaceholder: "Paste the target Job Description here...",
    clear: "Clear",
    yourResume: "Your Resume",
    uploadResume: "Upload Resume",
    uploadProject: "Upload Project/Portfolio",
    uploadTip: ".docx, .pdf",
    uploadImageTip: "Image files (.jpeg, .png, etc.)",
    analyzeProject: "Analyze Project",
    optimizeResume: "Optimize Resume",
    generateBtn: "Generate Optimized Resume",
    analyzing: "Analyzing...",
    matchScore: "Core Skills",
    basedOn: "Based on keyword matching & requirements",
    hardSkills: "Hard Skills Matched",
    softSkills: "Soft Skills Matched",
    diagnosis: "Critical Diagnosis",
    actionPlan: "Action Plan",
    previewMode: "Preview Mode",
    editMode: "Edit Mode",
    enableEditing: "Enable Editing",
    disableEditing: "Done Editing",
    downloadPdf: "Download PDF",
    downloadWord: "Export Word",
    templates: "Templates",
    accentColor: "Accent Color",
    backToEditor: "Back to Editor",
    editor: "Editor",
    customizeExport: "Customize & Export",
    zoom: "Zoom",
    changesSaved: "Changes saved automatically",
    aiRewrite: "AI Rewrite",
    addExperience: "+ Add Experience",
    addVolunteer: "+ Add Volunteer",
    addRole: "+ Add Role",
    addPage: "Add New Page",
    removePage: "Remove Page Break",
    education: "Education",
    references: "References",
    professionalSummary: "Professional Summary",
    coreCompetencies: "Core Competencies",
    professionalExperience: "Professional Experience",
    volunteerExperience: "Volunteer Experience",
    skills: "Skills",
    profile: "Profile",
    pageBreak: "Page Break",
    tabResume: "Resume",
    tabCoverLetter: "Cover Letter",
    missingKeywords: "Missing Keywords (ATS)",
    missingKeywordsTip: "Try adding these to your Skills or Experience:",
    linkedinPlaceholder: "linkedin.com/in/...",
    githubPlaceholder: "github.com/...",
    viewMode: "View Mode",
    addVolunteerLabel: "Add Volunteer Experience (Optional)",
    volunteerPlaceholder: "Paste details about your volunteer work, community service, or student society roles here...",
  },
  zh: {
    appTitle: "极速",
    appTitleSuffix: "简历",
    heroTitle: "几秒钟内",
    heroTitleHighlight: "优化您的简历",
    heroSubtitle: "粘贴您的目标职位描述，让 AI 为您量身定制简历，轻松通过 ATS 筛选并脱颖而出。",
    step1: "职位要求",
    step2: "上传",
    step3: "智能优化",
    jdLabel: "职位描述 (JD)",
    jdPlaceholder: "在此处粘贴目标职位描述...",
    clear: "清空",
    yourResume: "您的简历",
    uploadResume: "上传简历",
    uploadProject: "上传作品/项目",
    uploadTip: ".docx, .pdf",
    uploadImageTip: "图片文件 (.jpeg, .png等)",
    analyzeProject: "分析项目",
    optimizeResume: "优化简历",
    generateBtn: "生成优化简历",
    analyzing: "正在分析...",
    matchScore: "核心技能",
    basedOn: "基于关键词匹配和职位要求",
    hardSkills: "硬技能匹配",
    softSkills: "软技能匹配",
    diagnosis: "关键诊断",
    actionPlan: "行动计划",
    previewMode: "预览模式",
    editMode: "编辑模式",
    enableEditing: "启用编辑",
    disableEditing: "完成编辑",
    downloadPdf: "下载 PDF",
    downloadWord: "导出 Word",
    templates: "模版选择",
    accentColor: "主题颜色",
    backToEditor: "返回编辑器",
    editor: "编辑器",
    customizeExport: "定制与导出",
    zoom: "缩放",
    changesSaved: "更改已自动保存",
    aiRewrite: "AI 重写",
    addExperience: "+ 添加经历",
    addVolunteer: "+ 添加志愿经历",
    addRole: "+ 添加职位",
    addPage: "添加新页面",
    removePage: "删除分页线",
    education: "教育背景",
    references: "推荐人",
    professionalSummary: "职业总结",
    coreCompetencies: "核心竞争力",
    professionalExperience: "工作经历",
    volunteerExperience: "志愿经历",
    skills: "技能",
    profile: "个人简介",
    pageBreak: "分页线",
    tabResume: "简历",
    tabCoverLetter: "求职信",
    missingKeywords: "缺失关键词 (ATS)",
    missingKeywordsTip: "建议将这些词添加到技能或经历中：",
    linkedinPlaceholder: "linkedin.com/in/...",
    githubPlaceholder: "github.com/...",
    viewMode: "查看模式",
    addVolunteerLabel: "添加志愿经历 (可选)",
    volunteerPlaceholder: "在此处粘贴您的志愿服务、社区工作或领导经历详情...",
  }
};
